# Generated by Django 5.2.4 on 2025-07-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_exam_question_option_studentexam_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='target_class',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
    ]
