# Generated by Django 5.2.4 on 2025-07-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exam_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='status',
            field=models.CharField(choices=[('attempted', 'Attempted'), ('unattempted', 'Unattempted')], default='unattempted', max_length=20),
        ),
    ]
