# Generated by Django 5.2.4 on 2025-08-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
    ]
